### ISSUE TITLE
How are .exr files generated?

### ISSUE THREAD

**Issue by MEYE66** [ISET/isethdrsensor#2]
Hi, this is great work.
I want to know how these .exr files are generated, is this a render or taken with an HDR camera?

**Comment by wandell** [comment]
Many times we render in iset3d.  Mostly. There might be a stray camera image in the repository.

--------------------
Sent from my iPad
________________________________
From: MEYE66 ***@***.***>
Sent: Sunday, December 15, 2024 10:55:45 PM
To: ISET/isethdrsensor ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ISET/isethdrsensor] How are .exr files generated? (Issue #2)


Hi, this is great work.
I want to know how these .exr files are generated, is this a render or taken with an HDR camera?
